# Generated by Django 4.0.5 on 2022-06-09 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='contraseña',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulario',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
